### ISSUE TITLE
ImportError: No module named rpmUtils.miscutils

### ISSUE THREAD

**Issue by sorrowchen** [wied03/centos-package-cron#21]
Hi wied03, 
I‘m trying to use this tool in one of our 
CentOS release 6.5 (Final) Linux with Python 2.6.6, 
when I'm running this command:
` centos-package-cron`
Traceback (most recent call last):
  File "/usr/local/bin/centos-package-cron", line 7, in <module>
    from centos_package_cron.command_line import main
  File "/usr/local/lib/python2.7/site-packages/centos_package_cron/command_line.py", line 9, in <module>
    from report_producer import ReportProducer
  File "/usr/local/lib/python2.7/site-packages/centos_package_cron/report_producer.py", line 1, in <module>
    from annoyance_fetcher import AnnoyanceFetcher
  File "/usr/local/lib/python2.7/site-packages/centos_package_cron/annoyance_fetcher.py", line 1, in <module>
    from annoyance_check import AnnoyanceCheck
  File "/usr/local/lib/python2.7/site-packages/centos_package_cron/annoyance_check.py", line 1, in <module>
    from package import Package
  File "/usr/local/lib/python2.7/site-packages/centos_package_cron/package.py", line 4, in <module>
    from rpmUtils.miscutils import compareEVR
ImportError: No module named rpmUtils.miscutils

Is there any prerequisite dependency/plugins?

**Comment by wied03** [comment]
How did you install?

sent from my mobile device
